# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lab',
                'doc_host': 'https://zhenruiliao.github.io',
                'git_url': 'https://github.com/zhenruiliao/lab',
                'lib_path': 'lab'},
  'syms': {'lab.core': {'lab.core.foo': ('core.html#foo', 'lab/core.py')}}}
